#parameters configuration
mode: train
root: data/
predefined_dataset: MNIST
classes: ["MNIST", "CIFAR10"]
max_samples: null
batch_size: 32
num_workers: 0
device: cuda

#transforms configuration
transforms_config:
  train:
    Resize:
      - 32
      - 32
    RandomRotation: 90
    ToTensor:

  val:
    Resize:
      - 32
      - 32
    ToTensor:

  test:
    Resize:
      - 32
      - 32
    ToTensor:

  predict:
    Resize:
      - 32
      - 32
    ToTensor:

# target transforms configuration
target_transforms_config:
  train: null

  val: null

  test: null

  predict: null
